In [ ]:
df.isnull().sum()

In [ ]:
df = df[df['ESTU_PAIS_RESIDE'] == 'COLOMBIA']
df

In [ ]:
df['ESTU_DEPTO_RESIDE'].unique()

In [ ]:
# Sale "Bogota" y "Bogotá"
display(df['COLE_DEPTO_UBICACION'].unique())
df['COLE_DEPTO_UBICACION'].replace({'BOGOTA': 'BOGOTÁ'}, inplace=True)

In [1]:
import pandas as pd

In [11]:
display(df['COLE_DEPTO_UBICACION'].unique())

array(['HUILA', 'VALLE', 'ANTIOQUIA', 'TOLIMA', 'SANTANDER', 'BOLIVAR',
       'MAGDALENA', 'NARIÑO', 'CUNDINAMARCA', 'CASANARE', 'BOGOTÁ',
       'NORTE SANTANDER', 'CALDAS', 'BOYACA', 'CHOCO', 'CORDOBA', 'SUCRE',
       'CESAR', 'META', 'ATLANTICO', 'CAUCA', 'CAQUETA', 'RISARALDA',
       'LA GUAJIRA', 'QUINDIO', 'PUTUMAYO', 'GUAVIARE', 'AMAZONAS',
       'ARAUCA', 'VICHADA', 'SAN ANDRES', 'VAUPES', 'GUAINIA'],
      dtype=object)

In [12]:
df.to_csv('data/Resultados_Saber_11_nonull.csv', index=False)

In [13]:
pd.read_csv('data/Resultados_Saber_11_nonull.csv')

,PERIODO,ESTU_TIPODOCUMENTO,ESTU_CONSECUTIVO,COLE_AREA_UBICACION,COLE_BILINGUE,COLE_CALENDARIO,COLE_CARACTER,COLE_COD_DANE_ESTABLECIMIENTO,COLE_COD_DANE_SEDE,COLE_COD_DEPTO_UBICACION,...,FAMI_TIENECOMPUTADOR,FAMI_TIENEINTERNET,FAMI_TIENELAVADORA,DESEMP_INGLES,PUNT_INGLES,PUNT_MATEMATICAS,PUNT_SOCIALES_CIUDADANAS,PUNT_C_NATURALES,PUNT_LECTURA_CRITICA,PUNT_GLOBAL
0,20194,TI,SB11201940464873,RURAL,N,A,TÉCNICO/ACADÉMICO,1.410160e+11,2.410160e+11,41.0,...,Si,Si,Si,B1,71.0,66.0,70.0,65.0,69.0,339.0
1,20194,TI,SB11201940464873,RURAL,N,A,TÉCNICO/ACADÉMICO,1.410160e+11,2.410160e+11,41.0,...,Si,Si,Si,B1,71.0,66.0,70.0,65.0,69.0,339.0
2,20194,TI,SB11201940562856,URBANO,N,A,TÉCNICO/ACADÉMICO,1.413960e+11,1.413960e+11,41.0,...,No,No,No,A-,46.0,43.0,31.0,40.0,43.0,199.0
3,20194,TI,SB11201940562856,URBANO,N,A,TÉCNICO/ACADÉMICO,1.413960e+11,1.413960e+11,41.0,...,No,No,No,A-,46.0,43.0,31.0,40.0,43.0,199.0
4,20162,TI,SB11201620084846,URBANO,N,A,TÉCNICO/ACADÉMICO,1.760010e+11,1.760010e+11,76.0,...,Si,Si,Si,A2,59.0,57.0,46.0,57.0,57.0,272.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3584317,20221,CC,AC202210023501,URBANO,N,OTRO,ACADÉMICO,3.050010e+11,3.050010e+11,5.0,...,Si,Si,Si,A-,42.0,50.0,45.0,40.0,52.0,232.0
3584318,20221,TI,AC202210003698,URBANO,S,B,ACADÉMICO,3.110011e+11,3.110011e+11,11.0,...,Si,Si,Si,B1,76.0,55.0,54.0,56.0,56.0,284.0
3584319,20221,CC,AC202210034448,URBANO,N,A,ACADÉMICO,3.110011e+11,3.110011e+11,11.0,...,Si,Si,Si,A1,48.0,53.0,38.0,45.0,50.0,233.0
3584320,20221,TI,AC202210006814,URBANO,S,B,TÉCNICO/ACADÉMICO,3.110010e+11,3.110010e+11,11.0,...,Si,Si,Si,B1,73.0,67.0,57.0,62.0,63.0,315.0
3584321,20221,CC,AC202210029659,URBANO,N,A,ACADÉMICO,3.110011e+11,3.110011e+11,11.0,...,Si,Si,Si,A-,38.0,35.0,35.0,45.0,37.0,190.0