In [9]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from copy import copy

In [10]:
df = pd.read_csv('data/Resultados__nicos_Saber_11_20240719.csv')
df

C:\Users\JuanD\AppData\Local\Temp\ipykernel_18720\1033154861.py:1: DtypeWarning: Columns (45,46) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('data/Resultados__nicos_Saber_11_20240719.csv')

,PERIODO,ESTU_TIPODOCUMENTO,ESTU_CONSECUTIVO,COLE_AREA_UBICACION,COLE_BILINGUE,COLE_CALENDARIO,COLE_CARACTER,COLE_COD_DANE_ESTABLECIMIENTO,COLE_COD_DANE_SEDE,COLE_COD_DEPTO_UBICACION,...,FAMI_TIENECOMPUTADOR,FAMI_TIENEINTERNET,FAMI_TIENELAVADORA,DESEMP_INGLES,PUNT_INGLES,PUNT_MATEMATICAS,PUNT_SOCIALES_CIUDADANAS,PUNT_C_NATURALES,PUNT_LECTURA_CRITICA,PUNT_GLOBAL
0,20131,CR,SB11201310000414,URBANO,N,B,ACADÉMICO,3.118480e+11,3.118480e+11,11.0,...,Si,Si,Si,B+,94.0,88.0,NaN,NaN,NaN,NaN
1,20194,TI,SB11201940464873,RURAL,N,A,TÉCNICO/ACADÉMICO,1.410160e+11,2.410160e+11,41.0,...,Si,Si,Si,B1,71.0,66.0,70.0,65.0,69.0,339.0
2,20194,TI,SB11201940464873,RURAL,N,A,TÉCNICO/ACADÉMICO,1.410160e+11,2.410160e+11,41.0,...,Si,Si,Si,B1,71.0,66.0,70.0,65.0,69.0,339.0
3,20122,TI,SB11201220204399,URBANO,N,A,TÉCNICO/ACADÉMICO,1.631300e+11,1.631300e+11,63.0,...,Si,Si,No,A1,48.0,45.0,NaN,NaN,NaN,NaN
4,20132,TI,SB11201320464198,URBANO,N,A,TÉCNICO,1.190010e+11,1.190010e+11,19.0,...,Si,Si,Si,A-,43.0,52.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7109699,20221,TI,AC202210003698,URBANO,S,B,ACADÉMICO,3.110011e+11,3.110011e+11,11.0,...,Si,Si,Si,B1,76.0,55,54.0,56.0,56.0,284.0
7109700,20221,CC,AC202210034448,URBANO,N,A,ACADÉMICO,3.110011e+11,3.110011e+11,11.0,...,Si,Si,Si,A1,48.0,53,38.0,45.0,50.0,233.0
7109701,20221,TI,AC202210006814,URBANO,S,B,TÉCNICO/ACADÉMICO,3.110010e+11,3.110010e+11,11.0,...,Si,Si,Si,B1,73.0,67,57.0,62.0,63.0,315.0
7109702,20221,CC,AC202210029659,URBANO,N,A,ACADÉMICO,3.110011e+11,3.110011e+11,11.0,...,Si,Si,Si,A-,38.0,35,35.0,45.0,37.0,190.0
7109703,20221,CC,AC202210031563,URBANO,N,B,ACADÉMICO,3.520010e+11,3.520010e+11,52.0,...,NaN,Si,NaN,A1,49.0,56,53.0,54.0,50.0,265.0

In [11]:
df.isnull().sum()

PERIODO                                0
ESTU_TIPODOCUMENTO                     1
ESTU_CONSECUTIVO                       0
COLE_AREA_UBICACION                 3031
COLE_BILINGUE                     916870
COLE_CALENDARIO                     1536
COLE_CARACTER                     110212
COLE_COD_DANE_ESTABLECIMIENTO       3377
COLE_COD_DANE_SEDE                   110
COLE_COD_DEPTO_UBICACION              23
COLE_COD_MCPIO_UBICACION              23
COLE_CODIGO_ICFES                  23733
COLE_DEPTO_UBICACION                  23
COLE_GENERO                           23
COLE_JORNADA                          23
COLE_MCPIO_UBICACION                  23
COLE_NATURALEZA                       23
COLE_NOMBRE_ESTABLECIMIENTO           23
COLE_NOMBRE_SEDE                      23
COLE_SEDE_PRINCIPAL                   23
ESTU_COD_DEPTO_PRESENTACION           86
ESTU_COD_MCPIO_PRESENTACION           86
ESTU_COD_RESIDE_DEPTO              39594
ESTU_COD_RESIDE_MCPIO              39594
ESTU_DEPTO_PRESENTACION               86
ESTU_DEPTO_RESIDE                  39594
ESTU_ESTADOINVESTIGACION               0
ESTU_ESTUDIANTE                        0
ESTU_FECHANACIMIENTO                 165
ESTU_GENERO                         3406
ESTU_MCPIO_PRESENTACION               86
ESTU_MCPIO_RESIDE                  39594
ESTU_NACIONALIDAD                      0
ESTU_PAIS_RESIDE                       0
ESTU_PRIVADO_LIBERTAD                  0
FAMI_CUARTOSHOGAR                 128762
FAMI_EDUCACIONMADRE               212826
FAMI_EDUCACIONPADRE               212423
FAMI_ESTRATOVIVIENDA              218219
FAMI_PERSONASHOGAR                128228
FAMI_TIENEAUTOMOVIL               134769
FAMI_TIENECOMPUTADOR              151217
FAMI_TIENEINTERNET                191624
FAMI_TIENELAVADORA                128086
DESEMP_INGLES                       5410
PUNT_INGLES                         4179
PUNT_MATEMATICAS                       0
PUNT_SOCIALES_CIUDADANAS         2609523
PUNT_C_NATURALES                 2609523
PUNT_LECTURA_CRITICA             2609523
PUNT_GLOBAL                      2609523
dtype: int64

## Limpieza

Al igual que con saber pro, quedarnos unicamente con los estudiantes que residen en Colombia y eliminar los datos nulos

In [12]:
df = df[df['ESTU_PAIS_RESIDE'] == 'COLOMBIA']
df

,PERIODO,ESTU_TIPODOCUMENTO,ESTU_CONSECUTIVO,COLE_AREA_UBICACION,COLE_BILINGUE,COLE_CALENDARIO,COLE_CARACTER,COLE_COD_DANE_ESTABLECIMIENTO,COLE_COD_DANE_SEDE,COLE_COD_DEPTO_UBICACION,...,FAMI_TIENECOMPUTADOR,FAMI_TIENEINTERNET,FAMI_TIENELAVADORA,DESEMP_INGLES,PUNT_INGLES,PUNT_MATEMATICAS,PUNT_SOCIALES_CIUDADANAS,PUNT_C_NATURALES,PUNT_LECTURA_CRITICA,PUNT_GLOBAL
0,20131,CR,SB11201310000414,URBANO,N,B,ACADÉMICO,3.118480e+11,3.118480e+11,11.0,...,Si,Si,Si,B+,94.0,88.0,NaN,NaN,NaN,NaN
1,20194,TI,SB11201940464873,RURAL,N,A,TÉCNICO/ACADÉMICO,1.410160e+11,2.410160e+11,41.0,...,Si,Si,Si,B1,71.0,66.0,70.0,65.0,69.0,339.0
2,20194,TI,SB11201940464873,RURAL,N,A,TÉCNICO/ACADÉMICO,1.410160e+11,2.410160e+11,41.0,...,Si,Si,Si,B1,71.0,66.0,70.0,65.0,69.0,339.0
3,20122,TI,SB11201220204399,URBANO,N,A,TÉCNICO/ACADÉMICO,1.631300e+11,1.631300e+11,63.0,...,Si,Si,No,A1,48.0,45.0,NaN,NaN,NaN,NaN
4,20132,TI,SB11201320464198,URBANO,N,A,TÉCNICO,1.190010e+11,1.190010e+11,19.0,...,Si,Si,Si,A-,43.0,52.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7109699,20221,TI,AC202210003698,URBANO,S,B,ACADÉMICO,3.110011e+11,3.110011e+11,11.0,...,Si,Si,Si,B1,76.0,55,54.0,56.0,56.0,284.0
7109700,20221,CC,AC202210034448,URBANO,N,A,ACADÉMICO,3.110011e+11,3.110011e+11,11.0,...,Si,Si,Si,A1,48.0,53,38.0,45.0,50.0,233.0
7109701,20221,TI,AC202210006814,URBANO,S,B,TÉCNICO/ACADÉMICO,3.110010e+11,3.110010e+11,11.0,...,Si,Si,Si,B1,73.0,67,57.0,62.0,63.0,315.0
7109702,20221,CC,AC202210029659,URBANO,N,A,ACADÉMICO,3.110011e+11,3.110011e+11,11.0,...,Si,Si,Si,A-,38.0,35,35.0,45.0,37.0,190.0
7109703,20221,CC,AC202210031563,URBANO,N,B,ACADÉMICO,3.520010e+11,3.520010e+11,52.0,...,NaN,Si,NaN,A1,49.0,56,53.0,54.0,50.0,265.0

In [13]:
df['ESTU_DEPTO_RESIDE'].unique()

array(['BOGOTÁ', 'HUILA', 'QUINDIO', 'CAUCA', 'VALLE', 'TOLIMA',
       'ANTIOQUIA', 'PUTUMAYO', 'SANTANDER', 'ATLANTICO', 'CAQUETA',
       'SUCRE', 'BOYACA', 'BOLIVAR', 'CESAR', 'MAGDALENA',
       'NORTE SANTANDER', 'NARIÑO', 'CUNDINAMARCA', nan, 'CASANARE',
       'META', 'CALDAS', 'CHOCO', 'CORDOBA', 'RISARALDA', 'VICHADA',
       'LA GUAJIRA', 'ARAUCA', 'AMAZONAS', 'GUAVIARE', 'SAN ANDRES',
       'GUAINIA', 'VAUPES', 'EXTRANJERO'], dtype=object)

In [14]:
# Sale "Bogota" y "Bogotá"
display(df['COLE_DEPTO_UBICACION'].unique())
df['COLE_DEPTO_UBICACION'].replace({'BOGOTA': 'BOGOTÁ'}, inplace=True)

array(['BOGOTA', 'HUILA', 'QUINDIO', 'CAUCA', 'VALLE', 'TOLIMA',
       'ANTIOQUIA', 'PUTUMAYO', 'SANTANDER', 'ATLANTICO', 'CAQUETA',
       'SUCRE', 'BOYACA', 'BOLIVAR', 'CESAR', 'BOGOTÁ', 'MAGDALENA',
       'NORTE SANTANDER', 'NARIÑO', 'CUNDINAMARCA', 'CASANARE', 'META',
       'CALDAS', 'CHOCO', 'CORDOBA', 'RISARALDA', 'VICHADA', 'LA GUAJIRA',
       'AMAZONAS', 'ARAUCA', 'GUAVIARE', 'VAUPES', 'SAN ANDRES',
       'GUAINIA', nan], dtype=object)

C:\Users\JuanD\AppData\Local\Temp\ipykernel_18720\3297943151.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['COLE_DEPTO_UBICACION'].replace({'BOGOTA': 'BOGOTÁ'}, inplace=True)

In [15]:
df['COLE_DEPTO_UBICACION'].unique()

array(['BOGOTÁ', 'HUILA', 'QUINDIO', 'CAUCA', 'VALLE', 'TOLIMA',
       'ANTIOQUIA', 'PUTUMAYO', 'SANTANDER', 'ATLANTICO', 'CAQUETA',
       'SUCRE', 'BOYACA', 'BOLIVAR', 'CESAR', 'MAGDALENA',
       'NORTE SANTANDER', 'NARIÑO', 'CUNDINAMARCA', 'CASANARE', 'META',
       'CALDAS', 'CHOCO', 'CORDOBA', 'RISARALDA', 'VICHADA', 'LA GUAJIRA',
       'AMAZONAS', 'ARAUCA', 'GUAVIARE', 'VAUPES', 'SAN ANDRES',
       'GUAINIA', nan], dtype=object)

In [16]:
df.dropna(ignore_index=True, inplace=True)

C:\Users\JuanD\AppData\Local\Temp\ipykernel_18720\1062801506.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.dropna(ignore_index=True, inplace=True)

In [12]:
df.to_csv('data/Resultados_Saber_11_nonull.csv', index=False)

In [17]:
pd.read_csv('data/Resultados_Saber_11_nonull.csv')

,PERIODO,ESTU_TIPODOCUMENTO,ESTU_CONSECUTIVO,COLE_AREA_UBICACION,COLE_BILINGUE,COLE_CALENDARIO,COLE_CARACTER,COLE_COD_DANE_ESTABLECIMIENTO,COLE_COD_DANE_SEDE,COLE_COD_DEPTO_UBICACION,...,FAMI_TIENECOMPUTADOR,FAMI_TIENEINTERNET,FAMI_TIENELAVADORA,DESEMP_INGLES,PUNT_INGLES,PUNT_MATEMATICAS,PUNT_SOCIALES_CIUDADANAS,PUNT_C_NATURALES,PUNT_LECTURA_CRITICA,PUNT_GLOBAL
0,20194,TI,SB11201940464873,RURAL,N,A,TÉCNICO/ACADÉMICO,1.410160e+11,2.410160e+11,41.0,...,Si,Si,Si,B1,71.0,66.0,70.0,65.0,69.0,339.0
1,20194,TI,SB11201940464873,RURAL,N,A,TÉCNICO/ACADÉMICO,1.410160e+11,2.410160e+11,41.0,...,Si,Si,Si,B1,71.0,66.0,70.0,65.0,69.0,339.0
2,20194,TI,SB11201940562856,URBANO,N,A,TÉCNICO/ACADÉMICO,1.413960e+11,1.413960e+11,41.0,...,No,No,No,A-,46.0,43.0,31.0,40.0,43.0,199.0
3,20194,TI,SB11201940562856,URBANO,N,A,TÉCNICO/ACADÉMICO,1.413960e+11,1.413960e+11,41.0,...,No,No,No,A-,46.0,43.0,31.0,40.0,43.0,199.0
4,20162,TI,SB11201620084846,URBANO,N,A,TÉCNICO/ACADÉMICO,1.760010e+11,1.760010e+11,76.0,...,Si,Si,Si,A2,59.0,57.0,46.0,57.0,57.0,272.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3584317,20221,CC,AC202210023501,URBANO,N,OTRO,ACADÉMICO,3.050010e+11,3.050010e+11,5.0,...,Si,Si,Si,A-,42.0,50.0,45.0,40.0,52.0,232.0
3584318,20221,TI,AC202210003698,URBANO,S,B,ACADÉMICO,3.110011e+11,3.110011e+11,11.0,...,Si,Si,Si,B1,76.0,55.0,54.0,56.0,56.0,284.0
3584319,20221,CC,AC202210034448,URBANO,N,A,ACADÉMICO,3.110011e+11,3.110011e+11,11.0,...,Si,Si,Si,A1,48.0,53.0,38.0,45.0,50.0,233.0
3584320,20221,TI,AC202210006814,URBANO,S,B,TÉCNICO/ACADÉMICO,3.110010e+11,3.110010e+11,11.0,...,Si,Si,Si,B1,73.0,67.0,57.0,62.0,63.0,315.0
3584321,20221,CC,AC202210029659,URBANO,N,A,ACADÉMICO,3.110011e+11,3.110011e+11,11.0,...,Si,Si,Si,A-,38.0,35.0,35.0,45.0,37.0,190.0